- name: Delete argo addtional project
  kubernetes.core.k8s:
    state: absent
    template: ./templates/argo_project_addtional.yml.j2
  with_nested:
    - "{{ ENV_LIST }}"
    - "{{ ADDITIONAL_ARGO }}"
