- name: Provisionning DSO
  hosts: localhost
  tasks:
    - name: Disclaimer
      ansible.builtin.debug:
        msg: "Attention ! La suppression d'un projet ne supprimes pas les applications Argo, utilisez d'abord le playbook 'delete_git_project.yml' pour les effacer"
    - include_role:
        name: "{{ item }}"
      loop:
        - ldap-delete-project
        # - sonar-provisioning-user TODO
        - keycloak-delete-project
        - keycloak-remove-group-user
        - quay-provisioning-setup
        - gitlab-delete-group
        - gitlab-remove-group-user # à vérifier
        - delete-namespace-openshift
        - create-user-openshift
        - argo-delete-project
        # - nexus-provision-project TODO
