- name: Dele git repository
  hosts: localhost
  tasks:
    - name: Suppression du projet Git
      include_role:
        name: gitlab-project-delete
      loop:
        - REPO_DEST: "{{ REPO_DEST }}"
      loop_control:
        loop_var: REPOSITORY
