- name: Provisionning DSO
  hosts: localhost
  tasks:
    - name: Disclaimer
      ansible.builtin.debug:
        msg: "Attention ! La suppression d'un projet ne supprimes pas les applications Argo, utilisez d'abord le playbook 'delete_git_project.yml' pour les effacer"
    - include_role:
        name: "{{ item }}"
      loop:
        - ldap-project-delete
        - sonar-user-delete
        - keycloak-group-leave
        - keycloak-project-delete
        - quay-setup-delete
        - gitlab-group-delete
        # - gitlab-group-leave
        - openshift-namespace-delete
        - argo-project-delete
        - nexus-project-delete
