- name: Provisionning DSO
  hosts: localhost
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - ldap-project-provisioning
        - ldap-user-provisioning
        - sonar-user-provisioning
        - keycloak-project-provisioning
        - keycloak-user-provisioning
        - quay-setup-provisioning
        - gitlab-project-provisioning
        - gitlab-user-provisioning
        - openshift-namespace-create
        - openshift-user-create
        - argo-project-provisioning
        - nexus-project-provisioning
