- name: Provisionning DSO
  hosts: localhost
  tasks:
    # - debug:
    #     msg: "{{ manageiq }}"
    # - set_fact:
    #     manageiq_api_url: "{{ manageiq.api_url }}"
    # #First tasks are important when launched by manageiq to get miq data
    # - import_role:
    #     name: manageiq
    #     tasks_from: get_admin_token.yml
    # - import_role:
    #     name: manageiq
    #     tasks_from: get_request_input.yml

    # - name: set variables to be used by playbooks from MIQ dialog
    #   set_fact:
    #     ORGANIZATION_NAME: "{{ manageiq_request_dialog.dialog_ORGANIZATION_NAME }}"
    #     PROJECT_NAME: "{{ manageiq_request_dialog.dialog_PROJECT_NAME }}"
    #     LEVEL: "{{ manageiq_request_dialog.dialog_LEVEL }}"
    #     EMAIL: "{{ manageiq_request_dialog.dialog_EMAIL }}"

    - include_role:
        name: "{{ item }}"
      loop:
         - keycloak-provisioning-project
         - keycloak-provisioning-user
         - ldap-provisioning-user
         - gitlab-provisioning-user
         - create-user-openshift
