- name: Delete org group {{ FINAL_NAME }}
  ldap_entry:
    state: absent
    dn: "cn={{ FINAL_NAME }},ou=users,dc=example,dc=org"
    objectClass: groupOfNames
  args: "{{ LDAP_AUTH }}"

- name: Delete org group {{ FINAL_NAME }}-adm
  ldap_entry:
    state: absent
    dn: "cn={{ FINAL_NAME }}-adm,ou=users,dc=example,dc=org"
    objectClass: groupOfNames
  args: "{{ LDAP_AUTH }}"