- name: "Delete GitLab Group"
      community.general.gitlab_group:
        api_url: "{{ GITLAB_URL }}"
        api_token: "{{ GITLAB_TOKEN }}"
        validate_certs: false
        name: "{{ GROUP_NAME }}"
        #parent: "{{ PARENT_GROUP }}"
        state: absent
