---
# tasks file for keycloak-project-provisioning

- name: Delete a project admin group
  community.general.keycloak_group:
    name: "{{ FINAL_NAME }}-{{ item }}-RW"
    realm: "{{KC_REALM}}"
    state: absent
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ KC_API_URI }}/auth"
    auth_realm: master
    auth_username: "{{ KC_ADMIN }}"
    auth_password: "{{ KC_PASSWORD }}"
  with_items: "{{ ENV_LIST }}"

- name: Delete a project read group
  community.general.keycloak_group:
    name: "{{ FINAL_NAME }}-{{ item }}-RO"
    realm: "{{KC_REALM}}"
    state: absent
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ KC_API_URI }}/auth"
    auth_realm: master
    auth_username: "{{ KC_ADMIN }}"
    auth_password: "{{ KC_PASSWORD }}"
  with_items: "{{ ENV_LIST }}"
