- name: Create user to ldap
  ldap_entry:
    dn: "cn={{ EMAIL }},ou=users,dc=example,dc=org"
    objectClass: inetOrgPerson
    attributes: 
      cn: "{{ EMAIL }}"
      sn : "{{ EMAIL }}"
      mail: "{{ EMAIL }}"
      uid: "{{ EMAIL }}"
  args: "{{ LDAP_AUTH }}"