- name: Create argo default project
  kubernetes.core.k8s:
    state: present
    template: ./templates/argo_project.yml.j2
  with_items: "{{ ENV_LIST }}"

- name: Create argo addtional project
  kubernetes.core.k8s:
    state: present
    template: ./templates/argo_project_addtional.yml.j2
  with_nested:
    - "{{ ENV_LIST }}"
    - "{{ ADDITIONAL_ARGO }}"
